use egui::{Image, Rgba};

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Equipment {
    Helmet,
    Kevlar,
    AK47,
    AUG,
    AWP,
    Bizon,
    C4,
    CZ75,
    Deagle,
    Decoy,
    DefuseKit,
    DualBerettas,
    Famas,
    Fiveseven,
    Flashbang,
    G3SG1,
    Galil,
    Glock,
    HE,
    P200,
    Incendiary,
    M249,
    M4A1S,
    M4A1,
    Mac10,
    Mag7,
    Molotov,
    MP5SD,
    MP7,
    MP9,
    Negev,
    Nova,
    P2000,
    P250,
    P90,
    Revolver,
    SawedOff,
    SCAR20,
    SG556,
    Smoke,
    SSG08,
    Zeus,
    Tec9,
    UMP45,
    USPS,
    XM1014,
}

impl Equipment {
    pub fn as_str(&self) -> &'static str {
        match self {
            Equipment::Helmet => "helmet",
            Equipment::Kevlar => "kevlar",
            Equipment::AK47 => "ak47",
            Equipment::AUG => "aug",
            Equipment::AWP => "awp",
            Equipment::Bizon => "bizon",
            Equipment::C4 => "c4",
            Equipment::CZ75 => "cz75a",
            Equipment::Deagle => "deagle",
            Equipment::Decoy => "decoy",
            Equipment::DefuseKit => "defuser",
            Equipment::DualBerettas => "elite",
            Equipment::Famas => "famas",
            Equipment::Fiveseven => "fiveseven",
            Equipment::Flashbang => "flashbang",
            Equipment::G3SG1 => "g3sg1",
            Equipment::Galil => "galilar",
            Equipment::Glock => "glock",
            Equipment::HE => "hegrenade",
            Equipment::P200 => "hkp2000",
            Equipment::Incendiary => "incgrenade",
            Equipment::M249 => "m249",
            Equipment::M4A1S => "m4a1_silencer",
            Equipment::M4A1 => "m4a1",
            Equipment::Mac10 => "mac10",
            Equipment::Mag7 => "mag7",
            Equipment::Molotov => "molotov",
            Equipment::MP5SD => "mp5sd",
            Equipment::MP7 => "mp7",
            Equipment::MP9 => "mp9",
            Equipment::Negev => "negev",
            Equipment::Nova => "nova",
            Equipment::P2000 => "p2000",
            Equipment::P250 => "p250",
            Equipment::P90 => "p90",
            Equipment::Revolver => "revolver",
            Equipment::SawedOff => "sawedoff",
            Equipment::SCAR20 => "scar20",
            Equipment::SG556 => "sg556",
            Equipment::Smoke => "smokegrenade",
            Equipment::SSG08 => "ssg08",
            Equipment::Zeus => "taser",
            Equipment::Tec9 => "tec9",
            Equipment::UMP45 => "ump45",
            Equipment::USPS => "usp_silencer",
            Equipment::XM1014 => "xm1014",
        }
    }

    pub fn image(&self) -> Image<'_> {
        let img_src = match self {
            Equipment::Helmet => egui::include_image!("../../assets/equipment/helmet.svg"),
            Equipment::Kevlar => egui::include_image!("../../assets/equipment/kevlar.svg"),
            Equipment::AK47 => egui::include_image!("../../assets/equipment/ak47.svg"),
            Equipment::AUG => egui::include_image!("../../assets/equipment/aug.svg"),
            Equipment::AWP => egui::include_image!("../../assets/equipment/awp.svg"),
            Equipment::Bizon => egui::include_image!("../../assets/equipment/bizon.svg"),
            Equipment::C4 => egui::include_image!("../../assets/equipment/c4.svg"),
            Equipment::CZ75 => egui::include_image!("../../assets/equipment/cz75a.svg"),
            Equipment::Deagle => egui::include_image!("../../assets/equipment/deagle.svg"),
            Equipment::Decoy => egui::include_image!("../../assets/equipment/decoy.svg"),
            Equipment::DefuseKit => egui::include_image!("../../assets/equipment/defuser.svg"),
            Equipment::DualBerettas => egui::include_image!("../../assets/equipment/elite.svg"),
            Equipment::Famas => egui::include_image!("../../assets/equipment/famas.svg"),
            Equipment::Fiveseven => egui::include_image!("../../assets/equipment/fiveseven.svg"),
            Equipment::Flashbang => egui::include_image!("../../assets/equipment/flashbang.svg"),
            Equipment::G3SG1 => egui::include_image!("../../assets/equipment/g3sg1.svg"),
            Equipment::Galil => egui::include_image!("../../assets/equipment/galilar.svg"),
            Equipment::Glock => egui::include_image!("../../assets/equipment/glock.svg"),
            Equipment::HE => egui::include_image!("../../assets/equipment/hegrenade.svg"),
            Equipment::P200 => egui::include_image!("../../assets/equipment/hkp2000.svg"),
            Equipment::Incendiary => egui::include_image!("../../assets/equipment/incgrenade.svg"),
            Equipment::M249 => egui::include_image!("../../assets/equipment/m249.svg"),
            Equipment::M4A1S => egui::include_image!("../../assets/equipment/m4a1_silencer.svg"),
            Equipment::M4A1 => egui::include_image!("../../assets/equipment/m4a1.svg"),
            Equipment::Mac10 => egui::include_image!("../../assets/equipment/mac10.svg"),
            Equipment::Mag7 => egui::include_image!("../../assets/equipment/mag7.svg"),
            Equipment::Molotov => egui::include_image!("../../assets/equipment/molotov.svg"),
            Equipment::MP5SD => egui::include_image!("../../assets/equipment/mp5sd.svg"),
            Equipment::MP7 => egui::include_image!("../../assets/equipment/mp7.svg"),
            Equipment::MP9 => egui::include_image!("../../assets/equipment/mp9.svg"),
            Equipment::Negev => egui::include_image!("../../assets/equipment/negev.svg"),
            Equipment::Nova => egui::include_image!("../../assets/equipment/nova.svg"),
            Equipment::P2000 => egui::include_image!("../../assets/equipment/p2000.svg"),
            Equipment::P250 => egui::include_image!("../../assets/equipment/p250.svg"),
            Equipment::P90 => egui::include_image!("../../assets/equipment/p90.svg"),
            Equipment::Revolver => egui::include_image!("../../assets/equipment/revolver.svg"),
            Equipment::SawedOff => egui::include_image!("../../assets/equipment/sawedoff.svg"),
            Equipment::SCAR20 => egui::include_image!("../../assets/equipment/scar20.svg"),
            Equipment::SG556 => egui::include_image!("../../assets/equipment/sg556.svg"),
            Equipment::Smoke => {
                egui::include_image!("../../assets/equipment/smokegrenade.svg")
            }
            Equipment::SSG08 => egui::include_image!("../../assets/equipment/ssg08.svg"),
            Equipment::Zeus => egui::include_image!("../../assets/equipment/taser.svg"),
            Equipment::Tec9 => egui::include_image!("../../assets/equipment/tec9.svg"),
            Equipment::UMP45 => egui::include_image!("../../assets/equipment/ump45.svg"),
            Equipment::USPS => {
                egui::include_image!("../../assets/equipment/usp_silencer.svg")
            }
            Equipment::XM1014 => egui::include_image!("../../assets/equipment/xm1014.svg"),
        };

        Image::new(img_src).bg_fill(Rgba::TRANSPARENT)
    }
}
