
use egui::{Image, Rgba, SizeHint};

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Equipment {
    Ak47,
    ArmorHelmet,
    Armor,
    Aug,
    Awp,
    Bizon,
    C4,
    Cz75a,
    Deagle,
    Decoy,
    Defuser,
    Elite,
    Famas,
    Firebomb,
    Fiveseven,
    Flashbang,
    G3sg1,
    Galilar,
    Glock,
    Hegrenade,
    Helmet,
    Hkp2000,
    Incgrenade,
    Inferno,
    Kevlar,
    M249,
    M4a1Silencer,
    M4a1,
    Mac10,
    Mag7,
    Molotov,
    Mp5sd,
    Mp7,
    Mp9,
    Negev,
    Nova,
    P2000,
    P250,
    P90,
    Revolver,
    Sawedoff,
    Scar20,
    Sg556,
    Smokegrenade,
    Ssg08,
    Taser,
    Tec9,
    Ump45,
    UspSilencer,
    Xm1014,
}

impl Equipment {
    pub fn as_str(&self) -> &'static str {
        match self {
            Equipment::Ak47 => "ak47",
            Equipment::ArmorHelmet => "armor_helmet",
            Equipment::Armor => "armor",
            Equipment::Aug => "aug",
            Equipment::Awp => "awp",
            Equipment::Bizon => "bizon",
            Equipment::C4 => "c4",
            Equipment::Cz75a => "cz75a",
            Equipment::Deagle => "deagle",
            Equipment::Decoy => "decoy",
            Equipment::Defuser => "defuser",
            Equipment::Elite => "elite",
            Equipment::Famas => "famas",
            Equipment::Firebomb => "firebomb",
            Equipment::Fiveseven => "fiveseven",
            Equipment::Flashbang => "flashbang",
            Equipment::G3sg1 => "g3sg1",
            Equipment::Galilar => "galilar",
            Equipment::Glock => "glock",
            Equipment::Hegrenade => "hegrenade",
            Equipment::Helmet => "helmet",
            Equipment::Hkp2000 => "hkp2000",
            Equipment::Incgrenade => "incgrenade",
            Equipment::Inferno => "inferno",
            Equipment::Kevlar => "kevlar",
            Equipment::M249 => "m249",
            Equipment::M4a1Silencer => "m4a1_silencer",
            Equipment::M4a1 => "m4a1",
            Equipment::Mac10 => "mac10",
            Equipment::Mag7 => "mag7",
            Equipment::Molotov => "molotov",
            Equipment::Mp5sd => "mp5sd",
            Equipment::Mp7 => "mp7",
            Equipment::Mp9 => "mp9",
            Equipment::Negev => "negev",
            Equipment::Nova => "nova",
            Equipment::P2000 => "p2000",
            Equipment::P250 => "p250",
            Equipment::P90 => "p90",
            Equipment::Revolver => "revolver",
            Equipment::Sawedoff => "sawedoff",
            Equipment::Scar20 => "scar20",
            Equipment::Sg556 => "sg556",
            Equipment::Smokegrenade => "smokegrenade",
            Equipment::Ssg08 => "ssg08",
            Equipment::Taser => "taser",
            Equipment::Tec9 => "tec9",
            Equipment::Ump45 => "ump45",
            Equipment::UspSilencer => "usp_silencer",
            Equipment::Xm1014 => "xm1014",
        }
    }

    pub fn image(&self) -> Image<'_> { 
        let img_src = match self { 
            Equipment::Ak47 => egui::include_image!("../../assets/equipment/ak47.svg"),
            Equipment::ArmorHelmet => egui::include_image!("../../assets/equipment/armor_helmet.svg"),
            Equipment::Armor => egui::include_image!("../../assets/equipment/armor.svg"),
            Equipment::Aug => egui::include_image!("../../assets/equipment/aug.svg"),
            Equipment::Awp => egui::include_image!("../../assets/equipment/awp.svg"),
            Equipment::Bizon => egui::include_image!("../../assets/equipment/bizon.svg"),
            Equipment::C4 => egui::include_image!("../../assets/equipment/c4.svg"),
            Equipment::Cz75a => egui::include_image!("../../assets/equipment/cz75a.svg"),
            Equipment::Deagle => egui::include_image!("../../assets/equipment/deagle.svg"),
            Equipment::Decoy => egui::include_image!("../../assets/equipment/decoy.svg"),
            Equipment::Defuser => egui::include_image!("../../assets/equipment/defuser.svg"),
            Equipment::Elite => egui::include_image!("../../assets/equipment/elite.svg"),
            Equipment::Famas => egui::include_image!("../../assets/equipment/famas.svg"),
            Equipment::Firebomb => egui::include_image!("../../assets/equipment/firebomb.svg"),
            Equipment::Fiveseven => egui::include_image!("../../assets/equipment/fiveseven.svg"),
            Equipment::Flashbang => egui::include_image!("../../assets/equipment/flashbang.svg"),
            Equipment::G3sg1 => egui::include_image!("../../assets/equipment/g3sg1.svg"),
            Equipment::Galilar => egui::include_image!("../../assets/equipment/galilar.svg"),
            Equipment::Glock => egui::include_image!("../../assets/equipment/glock.svg"),
            Equipment::Hegrenade => egui::include_image!("../../assets/equipment/hegrenade.svg"),
            Equipment::Helmet => egui::include_image!("../../assets/equipment/helmet.svg"),
            Equipment::Hkp2000 => egui::include_image!("../../assets/equipment/hkp2000.svg"),
            Equipment::Incgrenade => egui::include_image!("../../assets/equipment/incgrenade.svg"),
            Equipment::Inferno => egui::include_image!("../../assets/equipment/inferno.svg"),
            Equipment::Kevlar => egui::include_image!("../../assets/equipment/kevlar.svg"),
            Equipment::M249 => egui::include_image!("../../assets/equipment/m249.svg"),
            Equipment::M4a1Silencer => egui::include_image!("../../assets/equipment/m4a1_silencer.svg"),
            Equipment::M4a1 => egui::include_image!("../../assets/equipment/m4a1.svg"),
            Equipment::Mac10 => egui::include_image!("../../assets/equipment/mac10.svg"),
            Equipment::Mag7 => egui::include_image!("../../assets/equipment/mag7.svg"),
            Equipment::Molotov => egui::include_image!("../../assets/equipment/molotov.svg"),
            Equipment::Mp5sd => egui::include_image!("../../assets/equipment/mp5sd.svg"),
            Equipment::Mp7 => egui::include_image!("../../assets/equipment/mp7.svg"),
            Equipment::Mp9 => egui::include_image!("../../assets/equipment/mp9.svg"),
            Equipment::Negev => egui::include_image!("../../assets/equipment/negev.svg"),
            Equipment::Nova => egui::include_image!("../../assets/equipment/nova.svg"),
            Equipment::P2000 => egui::include_image!("../../assets/equipment/p2000.svg"),
            Equipment::P250 => egui::include_image!("../../assets/equipment/p250.svg"),
            Equipment::P90 => egui::include_image!("../../assets/equipment/p90.svg"),
            Equipment::Revolver => egui::include_image!("../../assets/equipment/revolver.svg"),
            Equipment::Sawedoff => egui::include_image!("../../assets/equipment/sawedoff.svg"),
            Equipment::Scar20 => egui::include_image!("../../assets/equipment/scar20.svg"),
            Equipment::Sg556 => egui::include_image!("../../assets/equipment/sg556.svg"),
            Equipment::Smokegrenade => egui::include_image!("../../assets/equipment/smokegrenade.svg"),
            Equipment::Ssg08 => egui::include_image!("../../assets/equipment/ssg08.svg"),
            Equipment::Taser => egui::include_image!("../../assets/equipment/taser.svg"),
            Equipment::Tec9 => egui::include_image!("../../assets/equipment/tec9.svg"),
            Equipment::Ump45 => egui::include_image!("../../assets/equipment/ump45.svg"),
            Equipment::UspSilencer => egui::include_image!("../../assets/equipment/usp_silencer.svg"),
            Equipment::Xm1014 => egui::include_image!("../../assets/equipment/xm1014.svg")
        };
        

        
        Image::new(img_src).bg_fill(Rgba::TRANSPARENT)
    }
}